runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: public/index.html
  upload: /
- url: /css
  static_dir: public/css
- url: /fonts
  static_dir: public/fonts
- url: /js
  static_dir: public/js
- url: /img
  static_dir: public/img
- url: /(.*)/$
  static_files: public/\1/index.html
  upload: .*\.html$

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?
